config/routes.rb
Rails.application.routes.draw do

  get '/keyboards/my_keyboards', to: 'keyboards#index', as: 'my_keyboards'
  
  resources :keyboards

  resources :line_items, only: [:create, :edit, :update]
  resources :carts, only: [:show, :edit]
  resources :artists, only: [:show] do
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  #extend devise to use omniauth_callbacks controller 
  authenticated :user do
    root 'keyboards#index', as: 'authenticated_root'
  end

  resources :authentications, only: [:destroy]
  
  devise_scope :user do
    root 'devise/sessions#new'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :keyboards 

    validates :name, presence: true 
    validates :name, uniqueness: true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items
  has_many :keyboards, through: :line_items
  belongs_to :user

  def add_item(keyboard_id)
    line_item = self.line_items.find_by(keyboard_id: keyboard_id)

    if line_item
      line_item.quantity += 1
    else
      line_item = self.line_items.build(keyboard_id: keyboard_id)
    end

    self.update_inventory(keyboard_id) if line_item.keyboard.in_stock
    line_item.save
  end

  def update_inventory(keyboard_id, qty=1)
    keyboard = Keyboard.find(keyboard_id)
    keyboard.inventory -= qty if qty <= keyboard.inventory
    keyboard.for_sale = false if keyboard.inventory < 1
    keyboard.save
  end

  def total
    total = 0
    self.line_items.each do |line_item|
      keyboard = Keyboard.find(line_item.keyboard_id)
      total += (keyboard.price * line_item.quantity)
    end
    total
  end
end

app/models/keyboard.rb
class Keyboard < ApplicationRecord
    belongs_to :artist, required: false
    has_many :line_items
    has_many :carts, through: :line_items
    belongs_to :user, required: false
  
  
    validates :make, presence: true
    # validates :make, uniqueness: true
    validates :model, presence: true
    # validates :model, uniqueness: true
    validates :price, presence: true
    validates :inventory, presence: true

    # scope :for_sale, -> {where(for_sale: true)}
  
    def self.for_sale
      Keyboard.where("for_sale = ? AND inventory > ?", true, 0)
    end
  
    def self.for_sale_exclude_current_user(user)
      Keyboard.where.not("user_id = ?", user.id) & Keyboard.for_sale
    end
  
    def for_sale_display
      self.for_sale ? "yes" : "no"
    end
  
    def in_stock
      self.inventory > 0
    end
  
    def artist_attributes=(artist_attributes)
      if artist_id
        artist = Artist.find(artist_id)
      else
        artist = Artist.find_or_create_by(artist_attributes)
      end  
      self.artist = artist
    end

  end
  

app/models/line_item.rb
class LineItem < ApplicationRecord
    belongs_to :keyboard
    belongs_to :cart 
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]

  has_many :carts 
  has_many :keyboards

    def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.provider = auth.provider
      user.uid = auth.uid
      user.password = Devise.friendly_token[0,20]
    end
  end

  def apply_omniauth(auth)
    update_attributes(
      provider: auth.provider,
      uid: auth.uid
    )
  end

  def has_facebook_linked?
    self.provider.present? && self.uid.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  include CartsHelper
  
end
  

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
    
  def show
      @artist = Artist.find(params[:id])
    end
  end
  

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController

    def destroy
      current_user.update_attributes(provider: nil, uid: nil)
      redirect_to edit_user_registration_path, notice: "Facebook Account Unlinked"
    end
  end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @cart = current_cart
  end

  def edit
    @cart = Cart.find(params[:id])
  end 
end

app/controllers/keyboards_controller.rb
class KeyboardsController < ApplicationController

  def index
    @keyboards = current_user.keyboards
    render :index
  end

  def new
    if params[:artist_id] && !Artist.exists?(params[:artist_id])
      redirect_to store_path, alert: "Artist not found."
    elsif params[:artist_id] && Artist.exists?(params[:artist_id])
      @keyboard = Keyboard.new(artist_id: params[:artist_id])
    else
      @keyboard = Keyboard.new
    end
  end

  def create
    @keyboard = current_user.keyboards.build(keyboard_params)

    if @keyboard.save
      redirect_to keyboard_path(@keyboard)
    else
      render :new
    end
  end

  def show
    @keyboard = Keyboard.find(params[:id])
  end

  def edit
    @keyboard = current_user.keyboards.find_by(id: params[:id])
    if !@keyboard
      redirect_to keyboards_path
    end
  end

  def update
    @keyboard = current_user.keyboards.find(params[:id])

    @keyboard.update(keyboard_params)

    if @keyboard.save
      redirect_to keyboard_path(@keyboard)
    else
      render :edit
    end
  end

  def destroy
    current_user.keyboards.find(params[:id]).destroy
    redirect_to my_keyboards_path
  end


  private

  def keyboard_params
    params.require(:keyboard).permit(:make, :model, :price, :inventory, :for_sale, :artist_id, artist_attributes: [:name])
  end
  end
  

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  def create
    current_cart.add_item(params[:keyboard_id])
    if current_cart.save
      redirect_to cart_path(current_cart), {notice: 'Item added to cart!'}
    else
      redirect_to store_path, {alert: 'Item was not added. Please check inventory.'}
    end
  end

  def edit
    @line_item = LineItem.find(params[:id])
    render 'carts/edit'
  end

  def update
    lineitem = LineItem.find(params[:id])
    keyboard = lineitem.keyboard
    new_qty = params[:line_item][:quantity].to_i

    qty_update = new_qty - lineitem.quantity

    if keyboard.inventory >= qty_update
      if lineitem.update(lineitem_params)
        current_cart.update_inventory(keyboard.id, qty_update)
        redirect_to cart_path(current_cart), {notice: 'Item quantity was updated!'}
      else
        redirect_to store_path, {alert: 'Item quantity was not updated. Please check inventory.'}
      end
    else
      redirect_to cart_path(current_cart), {alert: 'Item quantity was not updated. Please check inventory.'}
    end
  end

  private

  def lineitem_params
    params.require(:line_item).permit(:quantity)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    if current_user.present?
      current_user.apply_omniauth(request.env["omniauth.auth"])
      redirect_to edit_user_registration_path, notice: "Facebook Account Linked!"
    else
      @user = User.from_omniauth(request.env["omniauth.auth"])
      sign_in_and_redirect @user
    end
  end

  private 

  def sign_up params 
    params.require(:user).permint(:name, :email, :password, :password_confirmation)
  end 

  def account_update_params
    params.require(:user).permin(:name, :email, :password, :password_confirmation, :current_password)
  end 
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
    def current_cart
        if cart = current_user.carts.find { |c| c.status != "submitted" }
          @cart = cart
        else
          @cart = current_user.carts.build
        end
      end
end

app/helpers/keyboards_helper.rb
module KeyboardsHelper
  def add_new_keyboard
    if @artist
      new_keyboard_path(@artist, @artist.keyboards.build)
    else
      new_keyboard_path
    end
  end
end

app/views/artists/show.html.erb
<% content_for :table_content do %>
    <%= render :partial => "keyboards/keyboard", :collection => @artist.keyboards %>
<% end %>

<%= render 'layouts/table' %>

app/views/carts/_cart_table.html.erb
<h1>Your Cart</h1>

<div class="container">
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Artist</th>
        <th scope="col">Make</th>
        <th scope="col">Price</th>
        <th scope="col">Qty</th>
        <th scope="col">Edit Qty</th>
      </tr>
    </thead>
    <tbody>

      <%= yield :cart_content %>

    </tbody>
  </table>
</div>

app/views/carts/_carts.html.erb
<h1>Your Cart</h1>

<div class="container">
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Artist</th>
        <th scope="col">Make</th>
        <th scope="col">Model</th>
        <th scope="col">Qty</th>
        <th scope="col">Edit Qty</th>
      </tr>
    </thead>
    <tbody>

      <%= yield :cart_content %>

    </tbody>
  </table>
</div>

app/views/carts/_line_item.html.erb
<tr>
  <th scope="col"><%= link_to line_item.keyboard.artist.name, artist_path(line_item.keyboard.artist) rescue nil %></th>
  <th scope="col"><%= link_to line_item.keyboard.make, keyboard_path(line_item.keyboard) rescue nil %></th>
  <th scope="col">$<%= line_item.keyboard.price %></th>
  <th scope="col"><%= line_item.quantity %></th>
  <th scope="col"><%= link_to "Edit", edit_line_item_path(line_item), class: 'btn btn-outline-secondary' %></th>
</tr>

app/views/carts/_line_items.html.erb
<tr>
  <th scope="col"><%= link_to line_item.keyboard.artist.name, artist_path(line_item.keyboard.artist) %></th>
  <th scope="col"><%= link_to line_item.keyboard.title, keyboard_path(line_item.keyboard) %></th>
  <th scope="col">$<%= line_item.keyboard.price %></th>
  <th scope="col"><%= line_item.quantity %></th>
  <th scope="col"><%= link_to "Edit", edit_line_item_path(line_item), class: 'btn btn-outline-secondary' %></th>
</tr>

app/views/carts/edit.html.erb
<%= form_for @line_item do |f| %>

    <% content_for :cart_content do %>
      <tr>
        <th scope="col"><%= link_to @line_item.keyboard.artist.name, artist_path(@line_item.keyboard.artist) %></th>
        <th scope="col"><%= link_to @line_item.keyboard.make, keyboard_path(@line_item.keyboard) %></th>
        <th scope="col">$<%= @line_item.keyboard.price %></th>
        <th scope="col"><%= f.text_field :quantity %></th>
        <th scope="col"><%= f.submit "Save", { class: 'btn btn-primary' } %></th>
      </tr>
    <% end %>
  
    <%= render 'carts/cart_table' %>
  
  <% end %>
  

app/views/carts/show.html.erb
<% content_for :cart_content do %>
  <%= render partial: 'line_item', collection: @cart.line_items %>
<% end %>

<%= render 'cart_table' %>

<h3>Order total: <strong>$<%= current_cart.total %></strong> </h3>

app/views/keyboards/_form.html.erb
<div class="container">
  <%= form_for keyboard do |f| %>
    <% if @keyboard.errors.any? %>
    <div class="alert alert-danger">
      <h4>The form contains <%= pluralize(@keyboard.errors.count, "error") %>:</h4>

      <ul>
      <% @keyboard.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>

    <div class="form-group">
    <%= f.label "Artist (select existing or create new)" %>
    <%= f.collection_select :artist_id, Artist.all, :id, :name, {include_blank: true}  %><br>
    <%= f.fields_for :artist, keyboard.build_artist do |artist_fields| %>
      <%= artist_fields.label :name, "New Artist Name" %>
      <%= artist_fields.text_field :name %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :make, "Make" %>
    <%= f.text_field :make %>
  </div>

  <div class="form-group">
  <%= f.label :model, "Model" %>
  <%= f.text_field :model %>
</div>

  <div class="form-group">
    <%= f.label :price, "Price" %>
    <%= f.text_field :price %>
  </div>

  <div class="form-group">
    <%= f.label :inventory, "Inventory" %>
    <%= f.text_field :inventory %>
  </div>

  <div class="form-group">
    <%= f.label :for_sale, "For Sale" %>
    <%= f.check_box :for_sale %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/keyboards/_keyboard.html.erb
<tr>
  <th scope="row"><%=  link_to keyboard.artist.name, artist_path(keyboard.artist)  %></th>
  <th scope="row"><%=  link_to keyboard.make, keyboard_path(keyboard)  %></th>
  <th scope="row"><%= keyboard.model %></th>
  <th scope="row">$<%= keyboard.price %></th>
  <th scope="row"><%= keyboard.inventory %></th>
  <th scope="row"><%= keyboard.for_sale_display %></th>
  <th scope="row">
  
    <% if current_user.keyboards.include?(keyboard) %>
      <%= link_to "Edit", edit_keyboard_path(keyboard), class: 'btn btn-outline-secondary' %></th>
      <th scope="row"><%= link_to "Delete", keyboard, method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-outline-secondary' %>
      <th scope="row"><%= button_to "Add to Cart", line_items_path(keyboard_id: keyboard), class: 'btn btn-primary' %>
    <% else %>
      <%= button_to "Add to Cart", line_items_path(keyboard_id: keyboard), class: 'btn btn-primary' %>
      <th scope="row"></th>
    <% end %>
  </th>
</tr>

app/views/keyboards/edit.html.erb
<h1>Edit Keyboard</h1>

<%= render partial: 'form', locals: {keyboard: @keyboard} %>

app/views/keyboards/index.html.erb
<% content_for :table_content do %>
    <%= render :partial => "keyboard", :collection => @keyboards %>
<% end %>

<%= render 'layouts/table' %>

app/views/keyboards/new.html.erb
<h1>Add New Keyboard</h1>

<%= render partial: 'form', locals: {keyboard: @keyboard} %>

app/views/keyboards/show.html.erb
<% content_for :table_content do %>
    <%= render partial: 'keyboard', locals: {keyboard: @keyboard} %>
<% end %>

<%= render 'layouts/table' %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">

     <nav>
        <ul class="nav navbar-nav navbar-left">
          <li id="logo"><%= "Tour Keyboards" %></li>
          
          <% if user_signed_in? %>
            <li><%= link_to "Marketplace", my_keyboards_path %></li>
            <li><%= link_to 'Add New Keyboard', add_new_keyboard %></li>
            <% if current_cart.persisted? %>
              <li><%= link_to "Cart", cart_path(current_cart) %></li>
            <% end %>
            <li><%= link_to 'Account', edit_user_registration_path, class: "navbar-link" %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
            
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
    </nav>
  </div>
</header>

app/views/layouts/_table.html.erb
<div class="container">
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Artist</th>
        <th scope="col">Make</th>
        <th scope="col">Model</th>
        <th scope="col">Price</th>
        <th scope="col">Qty</th>
        <th scope="col">For Sale</th>

      </tr>
    </thead
    <tbody>

      <%= yield :table_content %>

    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TourKeyboards</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    </div>
    <div class="container">
      <%= render 'layouts/header' %>
    </div>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>